# Faye
development:
  server: "http://localhost:9292/faye"
  adapter_javascript_url: "http://localhost:9292/faye/faye.js"
  auth_token: 21dqf13huir2fj23t5t
  adapter: "Faye"
  async: true

# Pusher
# development:
#   adapter_javascript_url: "http://js.pusher.com/2.0/pusher.min.js"
#   app_id: "YOUR_PUSHER_APP_ID"
#   api_key: "YOUR_PUSHER_API_KEY"
#   auth_token: "YOUR_PUSHER_SECRET"
#   adapter: "Pusher"
#   async: true

# Disabled
# development:
#   adapter: false

test:
  server: "http://localhost:9292/faye"
  adapter_javascript_url: "http://localhost:9292/faye/faye.js"
  adapter: "Faye"
  auth_token: "secret"
  async: false

production:
  server: "http://webchat-liulishuo.niclin.tw/faye"
  adapter_javascript_url: "http://webchat-liulishuo.niclin.tw/faye/faye.js"
  adapter: "Faye"
  auth_token: "0794942c3ca7aba370499839ab0f0ea33e5665cfac0fcf0455e91ece9dc7d101"
  async: true
